[[readings]]
author = "Peter Browns"
date = "2024-05-24"
title = "Den ville roboten"
format = "Høytlesing"

[[readings]]
author = "Aldous Huxley"
date = "2024-09-15"
title = "Brave new world"
format = "Bok"

[[readings]]
author = "Erlend Loe"
date = "2024-09-15"
title = "Kurt Kurér"
format = "Høytlesing"

[[readings]]
author = "J. R. R. Tolkien"
date = "2025-01-01"
title = "Hobbiten"
format = "Høytlesing"

[[readings]]
author = "Karl Ove Knausgård"
date = "2025-06-01"
title = "Nattskolen"
format = "Bok"

[[readings]]
author = "Walter Moers"
date = "2025-08-01"
title = "Kaptein Blåbjørns 13 1/2 liv"
format = "Høytlesing"

[[readings]]
author = "Cormac McCarthy"
date = "2025-09-01"
title = "Blodmeridianen"
format = "Lydbok"

[[readings]]
author = "Knut Hamsun"
date = "2025-10-05"
title = "Markens Grøde"
format = "Lydbok"

[[readings]]
author = "Tove Jansson"
date = "2025-07-01"
title = "Det usynlige barnet"
format = "Lydbok"

[[readings]]
author = "Nick Cutter"
date = "2024-05-26"
title = "The Deep"
format = "Lydbok"

[[readings]]
author = "Erlend Loe"
date = "2024-04-16"
title = "Giæver og lunker"
format = "Lydbok"

[[readings]]
author = "Peter Watts"
date = "2024-03-01"
title = "Blindsight"
format = "Lesebrett"

[[readings]]
author = "Peter Watts"
date = "2024-11-01"
title = "Starfish (Rifters #1)"
format = "Lesebrett"

[[readings]]
author = "Stephen King"
date = "2023-06-03"
title = "Det Mørke Tårn II"
format = "Lydbok"

[[readings]]
author = "George R.R. Martin"
date = "2023-10-23"
title = "Kongenes Kamp (En Sang om Is og Ild 2-1)"
format = "Lydbok"

[[readings]]
author = "Erlend Loe"
date = "2023-11-30"
title = "Drømmenes Sykkelregister"
format = "Lydbok"

[[readings]]
author = "George R.R. Martin"
date = "2024-02-07"
title = "Jern og Sand (En Sang om Is og Ild 5-2)"
format = "Lydbok"

[[readings]]
author = "George R.R. Martin"
date = "2024-01-04"
title = "Dragenes Dans (En Sang om Is og Ild 4-2)"
format = "Lydbok"

[[readings]]
author = "George R.R. Martin"
date = "2024-02-06"
title = "Drømmer og Støv (En Sang om Is og Ild 5-1)"
format = "Lydbok"

[[readings]]
author = "George R.R. Martin"
date = "2023-11-26"
title = "Blod og Gull (En Sang om Is og Ild 3-2)"
format = "Lydbok"

[[readings]]
author = "George R.R. Martin"
date = "2023-10-26"
title = "Stål og Snø (En Sang om Is og Ild 3-1)"
format = "Lydbok"

[[readings]]
author = "George R.R. Martin"
date = "2023-01-01"
title = "Kampen om jerntronen (En Sang om Is og Ild 1-2)"
format = "Lydbok"

[[readings]]
author = "Tove Jansson"
date = "2025-10-13"
title = "Farlig midtsommer"
format = "Bok"

[[readings]]
author = "J. K. Rowling"
date = "2026-01-10"
title = "Harry Potter og Mysteriekammeret"
format = "Høytlesing"

[[readings]]
author = "George R.R. Martin"
date = "2026-01-22"
title = "The Hedge Knight"
format = "Lydbok"
notes = "Ridder-feelgood med eit par tvistar. Lest av Rijen Laine"

[[readings]]
author = "George R.R. Martin"
date = "2026-01-23"
title = "The Sworn Sword"
format = "Lydbok"
notes = "Meire riddar-feelgood. Lest av Rijen Laine."

[[readings]]
author = "George R.R. Martin"
date = "2026-01-24"
title = "The Mystery Knight"
format = "Lydbok"
notes = "Endå meire riddar-feelgood. Lest av Rijen Laine. Finn den på YouTube"


[[readings]]
author = "Chuck Palahniuk"
date = "2026-02-03"
title = "Choke"
format = "Bok"
notes = "Om avhengighet. Og om å overgi seg? Tidlig totusentalls nihilsme."
